### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by yfcharm** [GhostCai/PortraitRelighting#5]
Great work!! I have a question after reading your paper: what is your training data? As you mentioned evaluation data in the paper, is it same as training data, I'm a little bit confused

**Comment by GhostCai** [comment]
Hi! The dataset was dynamically generated during training using [NeRFFaceLighting](https://github.com/IGLICT/NeRFFaceLighting) and SH lightings from FFHQ dataset, as detailed in the paper. Due to the extremely vast size of the data and storage constraints, we did not save a static version of the dataset. Instead, we recommend generating the data on-the-fly during training, which is a more practical and efficient approach.

It’s important to note that the evaluation data, which consists entirely of real-world data, is completely separate from the training data, which is synthetic.

Feel free to reach out if you have further questions!
